rudagames:
  api:
    base-url: https://api.rudagames.com
    sign-in: /login
    events: /events/dates
    locations: /locations
    cities: /locations/cities
    countries: /locations/countries
    accepted-games: /players/applications
    products: /products

  location:
    city: 54
    country: 10

  auth:
    email: ${RUDAGAMES_ACCOUNT_EMAIL}
    password: ${RUDAGAMES_ACCOUNT_PASSWORD}

  vk:
    team-chat-id: ${RUDAGAMES_VK_TEAM_CHAT_ID}
